rule:
  changelog_file: CHANGELOG.md
  active_profile: alpha profile

  profiles:
  - name: alpha profile
    extends: xconv_default
    tag:
      mode: alpha # alpha beta | default: standard
      format: v$version # v$major.$minor.$patch$"