rule:
  changelog_file: CHANGELOG.md
  active_profile: alpha profile

  profiles:
  - name: alpha profile
    extends: xconv_default
    tag:
      mode: alpha # alpha beta | default: standard
      format: v$version # v$major.$minor.$patch$"

    message_template: | 
      {{prefix}}({{scope}}): {{subject}}
      
      {% if body != '' %}
      {{body}}
      {% endif %}

      {% if is_breaking_change %}
      BREAKING CHANGE: 
      {% endif %}
      {% if footer != '' %}
      issue: {{footer}}
      {% endif %}