name: CI
on: 
  push:
    branches:
    - main
  pull_request: 
    branches:
    - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: [ '1.18' ]
        os: [ 'ubuntu-20.04', 'macos-10.15', 'windows-2019' ]   

    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code
      uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0
    
    - name: Go build
      run: |
        go build -o xc

    - name: Cache source code
      uses: actions/cache@v3.0.5
      env:
        cache-name: source-code
      with:
        path: |
          ./*
        key: build-${{ matrix.os }}-${{ matrix.go }}-${{ env.cache-name }}
  
  unit:
    needs:
      - build 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: [ '1.18' ] # Check the binary of the latest go version is enough
        os: [ 'ubuntu-20.04', 'macos-10.15', 'windows-2019' ]
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Run unit tests
        run: | 
          go test -v ./...
  
  upload:
    needs:
      - unit
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: [ '1.18' ] # Check the binary of the latest go version is enough
        os: [ 'ubuntu-20.04', 'macos-10.15', 'windows-2019' ]
    steps:
    - name: Cache node modules
      uses: actions/cache@v3.0.5
      env:
        cache-name: source-code
      with:
        path: |
          ./*
        key: build-${{ matrix.os }}-${{ matrix.go }}-${{ env.cache-name }}

    - uses: actions/upload-artifact@master
      name: Upload binary ${{ runner.os }}
      with:
        name: xc-${{ runner.os }}
        path: ./xconv*